services:
  wordpress_3Cp6:
    image: wordpress:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST_IP}:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 0
    ports:
      - ${HOST_IP}:${WORDPRESS_PORT}:80
    volumes:
      - ${APP_PATH}/html:/var/www/html
      - ${APP_PATH}/bt_custom.ini:/usr/local/etc/php/conf.d/bt_custom.ini
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true